version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      # Map the folder to /metabase-data in the container
      - ./data/sqlite:/metabase-data
